apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-terminating-diagnose
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-terminating-diagnose
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "persistentvolumes", "nodes", "events"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments", "csidrivers", "csinodes", "storageclasses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-terminating-diagnose
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-terminating-diagnose
subjects:
  - kind: ServiceAccount
    name: resource-terminating-diagnose
    namespace: kube-system
